# Generated by Django 2.1.4 on 2018-12-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('temp', models.CharField(max_length=30)),
                ('air_speed', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
